function(default_args MARCO DEFAULT_VALUE)
    if (NOT DEFINED ${MARCO})
        set(${MARCO} ${DEFAULT_VALUE} PARENT_SCOPE)
    else ()
        message(STATUS "${MARCO} overridden as `${${MARCO}}`")
        string(REPLACE " " ";" ${MARCO} "${${MARCO}}")
        set(${MARCO} ${${MARCO}} PARENT_SCOPE)
    endif ()
endfunction()
